# Generated by Django 6.0 on 2025-12-17 13:37

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                (
                    "summary",
                    models.TextField(
                        help_text="Short overview for cards.",
                        validators=[django.core.validators.MaxLengthValidator(500)],
                    ),
                ),
                ("content", models.TextField(help_text="Markdown supported")),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="portfolio/"),
                ),
                ("repository_url", models.URLField(blank=True, null=True)),
                ("live_demo_url", models.URLField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DR", "Draft"),
                            ("PB", "Published"),
                            ("AR", "Archived"),
                        ],
                        default="DR",
                        max_length=2,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="projects_pr_status_f023cb_idx"
                    ),
                    models.Index(
                        fields=["is_featured"], name="projects_pr_is_feat_bfabaf_idx"
                    ),
                    models.Index(fields=["slug"], name="projects_pr_slug_042165_idx"),
                ],
            },
        ),
    ]
