# Generated by Django 6.0.5 on 2026-05-25 15:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_project_projects_pr_created_6b02e3_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="Technology",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                (
                    "icon_name",
                    models.CharField(
                        blank=True,
                        help_text="Lucide or DevIcon class name (e.g., 'cisco', 'python', 'ansible')",
                        max_length=50,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Automation, Networking, Development, DevOps, Cloud",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name": "Technology",
                "verbose_name_plural": "Technologies",
                "ordering": ["name"],
            },
        ),
        migrations.RemoveField(
            model_name="project",
            name="technologies",
        ),
        migrations.AddField(
            model_name="project",
            name="technologies",
            field=models.ManyToManyField(
                blank=True,
                help_text="Selected technology tags for this project",
                related_name="projects",
                to="projects.technology",
            ),
        ),
    ]
