# Generated by Django 6.0.5 on 2026-05-30 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_technology_remove_project_technologies_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="claps_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of project claps",
                verbose_name="Claps Count",
            ),
        ),
    ]
