# Generated by Django 6.0.5 on 2026-05-30 22:16

import uuid

import django.db.models.deletion
from django.db import migrations, models


def seed_categories(apps, schema_editor):
    Category = apps.get_model("projects", "Category")
    categories = ["Networking", "Product", "Software dev", "System Admin"]
    from django.utils.text import slugify

    for cat_name in categories:
        Category.objects.get_or_create(
            name=cat_name, defaults={"slug": slugify(cat_name)}
        )


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_project_claps_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="project",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="projects.category",
                verbose_name="Category",
            ),
        ),
        migrations.RunPython(seed_categories),
    ]
