[project]
name = "portfolio-backend"
version = "0.1.0"
description = "Professional Django Portfolio API"
authors = [
    { name = "bonheurNE07", email = "bonheurndezenc@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.12, <4.0"
dependencies = [
    "django (>=6.0,<7.0)",
    "djangorestframework (>=3.16.1,<4.0.0)",
    "django-cors-headers (>=4.9.0,<5.0.0)",
    "python-decouple (>=3.8,<4.0)",
    "pillow (>=12.0.0,<13.0.0)",
    "djoser (>=2.3.3,<3.0.0)",
    "django-cloudinary-storage (>=0.3.0,<0.4.0)",
    "cloudinary (>=1.44.1,<2.0.0)",
    "django-filter (>=25.2,<26.0)",
    "whitenoise (>=6.11.0,<7.0.0)",
    "gunicorn (>=23.0.0,<24.0.0)",
    "psycopg2-binary (>=2.9.11,<3.0.0)",
    "sendgrid (>=6.12.5,<7.0.0)"
]

[tool.uv]
package = false

[dependency-groups]
dev = [
    "black (>=25.12.0,<26.0.0)",
    "flake8 (>=7.3.0,<8.0.0)",
    "pytest (>=9.0.2,<10.0.0)",
    "pytest-django (>=4.11.1,<5.0.0)",
    "pre-commit (>=4.5.0,<5.0.0)"
]

# Configuration for Black to ensure line length matches standard
[tool.black]
line-length = 88
target-version = ['py312']
