# Generated by Django 6.0 on 2025-12-18 09:43

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                (
                    "summary",
                    models.TextField(
                        help_text="Short overview of the article",
                        validators=[django.core.validators.MaxLengthValidator(500)],
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Main content of the blog post in markdown format"
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="portfolio/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DF", "Draft"),
                            ("PB", "Published"),
                            ("AC", "Archived"),
                        ],
                        default="DF",
                        max_length=2,
                        verbose_name="Status",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_posts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
            ],
            options={
                "verbose_name": "Post",
                "verbose_name_plural": "Posts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status"], name="blog_post_status_02ce19_idx"),
                    models.Index(fields=["slug"], name="blog_post_slug_cdb902_idx"),
                ],
            },
        ),
    ]
