# Generated by Django 6.0 on 2025-12-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="reading_time",
            field=models.PositiveIntegerField(
                blank=True, help_text="Estimated reading time in minutes", null=True
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(
                help_text="Main content of the blog            post in markdown format"
            ),
        ),
    ]
